baseURL = "https://sevocrear.github.io/"
languageCode = "en-us"
paginate = 6 # Define the number of posts per page
theme = "portio"
title = "sevocrear"
defaultContentLanguageInSubdir = true

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
    contactLink = "en/contact"
    blogPageURL = "en/blog"
    [[languages.en.menu.main]]
    name = "Home"
    url = "#home"
    weight = 1
    [[languages.en.menu.main]]
    name = "About"
    url = "#about"
    weight = 2
    [[languages.en.menu.main]]
    name = "Service"
    url = "#service"
    weight = 3
    [[languages.en.menu.main]]
    name = "Work"
    url = "#portfolio"
    weight = 4
    [[languages.en.menu.main]]
    name = "Resume"
    url = "#resume"
    weight = 5
    [[languages.en.menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 6
    [[languages.en.menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 7

    # Sitemap Menu
    [[languages.en.menu.sitemap]]
    name = "About me"
    url = "#about"
    weight = 1
    #[[menu.sitemap]]
    #name = "Frequently Ask Question"
    #url = "#"
    #weight = 2
    #[[menu.sitemap]]
    #name = "Privacy & Policy"
    #url = "#"
    #weight = 3
    [[languages.en.menu.sitemap]]
    name = "Latest Article"
    url = "#blog"
    weight = 2

    [languages.en.params.address]
    address = "420500 Innopolis, Russia"
    email = "sevocrear@gmail.com"
    openingHours = "Open from 8 a.m. to 8 p.m."

  [languages.ru]
    languageName = "Russian"
    weight = 2
    # Main Menu
    [languages.ru.params]
    contactLink = "ru/contact"
    blogPageURL = "ru/blog"
    [[languages.ru.menu.main]]
    name = "Главная"
    url = "#home"
    weight = 1
    [[languages.ru.menu.main]]
    name = "Обо мне"
    url = "#about"
    weight = 2
    [[languages.ru.menu.main]]
    name = "Услуги"
    url = "#service"
    weight = 3
    [[languages.ru.menu.main]]
    name = "Портфолио"
    url = "#portfolio"
    weight = 4
    [[languages.ru.menu.main]]
    name = "Резюме"
    url = "#resume"
    weight = 5
    [[languages.ru.menu.main]]
    name = "Блог"
    url = "#blog"
    weight = 6
    [[languages.ru.menu.main]]
    name = "Контакты"
    url = "/contact"
    weight = 7


    # Sitemap Menu
    [[languages.ru.menu.sitemap]]
    name = "Обо мне"
    url = "#about"
    weight = 1
    #[[menu.sitemap]]
    #name = "Frequently Ask Question"
    #url = "#"
    #weight = 2
    #[[menu.sitemap]]
    #name = "Privacy & Policy"
    #url = "#"
    #weight = 3
    [[languages.ru.menu.sitemap]]
    name = "Последняя статья"
    url = "#blog"
    weight = 2

    [languages.ru.params.address]
    address = "420500 Иннополис, Россия"
    email = "sevocrear@gmail.com"
    openingHours = "Открыт для заявок с 8 до 20"

[params]
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/mzbkkzbe"
googleAnalytics = "G-RZPCD5E5NB"
logo = "images/site-navigation/logo.png"

[params.map]
APIkey = "AIzaSyBVD82A8IiQA-F2AeMAacdMtYO_Con5Hy0"
latitude = "55.752104"
longitude = "48.744557"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-vk"
url = "https://vk.com/sevocrear"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/ilya-sevostyanov-7abb671b0"
weight = 2
[[params.social]]
icon = "fa-git"
url = "https://github.com/sevocrear"
weight = 3
